### ISSUE TITLE
Clarification required on Speed Setting (Bytes per second)

### ISSUE THREAD

**Issue by sureshkvl** [nvf-crucio/PROX#2]
Hi,
I am setting the speed 1% (Equal to 12,500,000 Bytes per sec). 

How number of packets to be send are calculated from this Bytes per sec?. 
In case 50 bytes packet(including header and payload) means,  12,500,000/50 =  250,000 packets per second.  Is that correct?
But i could see around 148,000 packets per second. Why is that? 

Thanks
suresh

**Comment by crucio-io** [comment]
Hi Surehkvl, (From Lap)
>> How number of packets to be send are calculated from this Bytes per sec?.
It depends on your packet size.

The frame rate for 10 GbE is determined by a formula that divides the 10
billion bits per second by the
preamble + frame length + interframe gap
Preamble: 8 bytes * 8 = 64 bits
Frame length: 64 bytes (minimum) * 8 = 512 bits
Interframe gap: 12 bytes (minimum) * 8 = 96 bits

Therefore, Maximum Frame Rate (64-byte packets)
= MAX Transmit Bit Rate / (Preamble + Frame Length + Inter-frame Gap)
= 10,000,000,000 / (64 + 512 + 96)
= 10,000,000,000 / 672
= 14,880,952.38 frame per second (fps)

For your case, the speed 1% (Equal to 12,500,000 Bytes per sec) and packet
size is 50 bytes.
Theoretical, packet rate = 12,500,000/(8 + 50 + 12) = 178,571 packets per
second
This number is closer to the number you see.
However, for the 802.3 frame contains
Ethernet Header = 18 Bytes [Dst Mac(6) + Src Mac(6) + Length (2) +CRC(4)]
Minimum Data Portion = 46 Bytes
Minimum Ethernet Frame Size = 64 Bytes
(https://en.wikipedia.org/wiki/Ethernet_frame)
Frames must be at least 64 bytes long, (not including the preamble)
If the data field is shorter than 46 bytes, it must be compensated by the
Pad field.

Can you please try with packet size = 64 bytes to see if your numbers are
closer to the theoretical

**Comment by sureshkvl** [comment]
Thanks for the detailed answer.
My Packet is the one available with the  default gen.cfg, 
pkt inline=00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00 00 24 00 01 00 00 40 11 f7 7d ${gen_hex_ip} ${sut_hex_ip} 0b b8 0b b9 00 10 55 7b
I captured the in wireshark traces  and it shows the length as 50 bytes, 
 Ethernet 14 (without CRC) + IP(20) + UDP(8)+Payload (8)
So, this does not have Ethernet CRC included. if i include the CRC, the packet size will be 54 bytes.
As you mentioned, i will make it 64 and test.  
Again, Thanks for the detailed analysis and support.

One more Question :)

i use pkt_inline in the gen.cfg file, and on the fly (via command) i change the pkt_size to 100.  The behavior Prox  pads the Zeros (0) at the end of the packet to bring the packet size to 100.   This packet is invalid one with respect to L3/L4 protocol as IP Protocol header and UDP header required recalculation.
Is this the expected behavior?

Suppose, if i want to send 1400 bytes packet, I should mention the exact packet in "pkt_inline" option?
Is there any way we can generated the valid packet  on the fly(without restarting prox)?

Thanks
suresh

**Comment by lapnd** [comment]
Hello Suresh,
>>i use pkt_inline in the gen.cfg file, and on the fly (via command) i change the pkt_size to 100. The behavior Prox pads the Zeros (0) at the end of the packet to bring the packet size to 100. This packet is invalid one with respect to L3/L4 protocol as IP Protocol header and UDP header required recalculation.
>>Is this the expected behavior?

The first 38 bytes are Ethernet Header and IP header. They are unchanged.
PROX will pad Zero to the end of packet (IP payload section) and recalculate checksum.
The packet is still valid.

>> Suppose, if i want to send 1400 bytes packet, I should mention the exact packet in "pkt_inline" option?

A packet has 03 main sections:
- Header (includes Ethernet Header, IP header)
- Payload
- Checksum

You just need to fill minimal packet pattern, for example
70 00 00 00 00 01 70 00 00 00 00 02 08 00 45 00 00 1c 00 01 00 00 40 11 f7 7d c0 a8 01 01 c0 a8 01 01 13 88 13 88 00 08 55 7b
then set packet size to 1400 bytes, PROX will pad data to payload automatically.

I would recommend you check DATS (https://github.com/nvf-crucio/DATS) to see use cases on utilizing PROX as VNF-Load as well as Traffic Generator
(PROX configs are located at https://github.com/nvf-crucio/DATS/tree/master/tests/prox-configs)

>> Is there any way we can generated the valid packet on the fly(without restarting prox)?

As I mentioned above, you need to set correct Header section, PROX will do remain tasks (recalculate checksum, padding...)

Lapd,

**Comment by sureshkvl** [comment]
Thanks Lapd,  I could able to set the packet size on the fly, and it works.  Thanks for the support and pointer to DATS. I am looking in to it.  
PROX is really awesome utility for performance testing. I appreciate the hard work done :+1:
